DROP TABLE IF EXISTS `employee`;
CREATE TABLE `employee`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `SALARY` decimal(10, 2) NULL DEFAULT NULL,
  `DEPARTMENT_ID` int(11) NULL DEFAULT NULL,
  `DELETED` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
